/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.07 at 04:32:17 PM MSD
//

package com.aplana.dmsi.types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.aplana.dmsi.types.common.ImportedDocCard;

/**
 * <p>
 * Java class for AcknowledgementType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name=&quot;AcknowledgementType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}RegNumber&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}AckResult&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *         &lt;element ref=&quot;{}DocTransfer&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;msg_id&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;ask_type&quot; use=&quot;required&quot; type=&quot;{}AcknowledgementEnumType&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcknowledgementType", propOrder = { "regNumber", "ackResult", "docTransfer" })
public class AcknowledgementType extends DMSIObject {

    @XmlElement(name = "RegNumber")
    protected RegNumber regNumber;
    @XmlElement(name = "AckResult", required = true)
    protected List<AckResult> ackResult;
    @XmlElement(name = "DocTransfer")
    protected DocTransfer docTransfer;
    @XmlAttribute(name = "msg_id", required = true)
    protected String msgId = "";
    @XmlAttribute(name = "ack_type", required = true)
    protected AckType ackType;
    @XmlTransient
    private String ackResultDescription;
    @XmlTransient
	private Long ackResultErrorCode;
	@XmlTransient
    private ImportedDocCard importedDocCard;

    /**
     * Gets the value of the regNumber property.
     *
     * @return possible object is {@link RegNumber }
     *
     */
    public RegNumber getRegNumber() {
        return regNumber;
    }

    /**
     * Sets the value of the regNumber property.
     *
     * @param value
     *                allowed object is {@link RegNumber }
     *
     */
    public void setRegNumber(RegNumber value) {
        this.regNumber = value;
    }

    /**
     * Gets the value of the ackResult property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the ackResult property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getAckResult().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AckResult }
     *
     *
     */
    public List<AckResult> getAckResult() {
        if (ackResult == null) {
            ackResult = new ArrayList<AckResult>();
        }
		return ackResult;
    }

    public DocTransfer getDocTransfer() {
        return docTransfer;
    }

    public void setDocTransfer(DocTransfer value) {
        this.docTransfer = value;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String value) {
        this.msgId = value;
    }

    public AckType getAckType() {
        return ackType;
    }

    public void setAckType(AckType value) {
        this.ackType = value;
    }

    public String getAckResultDescription() {
        return this.ackResultDescription;
    }

    public void setAckResultDescription(String ackResultDescription) {
        this.ackResultDescription = ackResultDescription;
    }

	public Long getAckResultErrorCode() {
		return this.ackResultErrorCode;
	}

	public void setAckResultErrorCode(Long ackResultErrorCode) {
		this.ackResultErrorCode = ackResultErrorCode;
	}

    public ImportedDocCard getImportedDocCard() {
        return this.importedDocCard;
    }

    public void setImportedDocCard(ImportedDocCard importedDocCard) {
        this.importedDocCard = importedDocCard;
    }

}
