/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.07 at 04:32:17 PM MSD 
//

package com.aplana.dmsi.types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.aplana.dmsi.types.adapters.DocTransferAdapter;

/**
 * <p>
 * Java class for AddDocumentsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;AddDocumentsType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Folder&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref=&quot;{}DocTransfer&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *                   &lt;element ref=&quot;{}Note&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *                   &lt;element ref=&quot;{}Referred&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name=&quot;add_type&quot; use=&quot;required&quot; type=&quot;{}FolderAddEnumType&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddDocumentsType", propOrder = { "folder" })
public class AddDocumentsType {

    @XmlElement(name = "Folder")
    protected List<AddDocumentsType.Folder> folder;

    /**
     * Gets the value of the folder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the folder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     *    getFolder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddDocumentsType.Folder }
     * 
     * 
     */
    public List<AddDocumentsType.Folder> getFolder() {
        if (folder == null) {
            folder = new ArrayList<AddDocumentsType.Folder>();
        }
        return this.folder;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref=&quot;{}DocTransfer&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
     *         &lt;element ref=&quot;{}Note&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
     *         &lt;element ref=&quot;{}Referred&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name=&quot;add_type&quot; use=&quot;required&quot; type=&quot;{}FolderAddEnumType&quot; /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "docTransfer", "note", "referred" })
    public static class Folder {

        @XmlElement(name = "DocTransfer")
	@XmlJavaTypeAdapter(DocTransferAdapter.class)
        protected List<DocTransfer> docTransfer;
        @XmlElement(name = "Note")
        protected List<Note> note;
        @XmlElement(name = "Referred")
        protected List<Referred> referred;
	@XmlAttribute(name = "contents", required = true)
	protected String contents;
        @XmlAttribute(name = "add_type", required = true)
	protected FolderAddType addType;

        /**
         * Gets the value of the docTransfer property.
         * 
         * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the docTransfer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
	 *
         * <pre>
         *    getDocTransfer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocTransfer }
         * 
         * 
         */
        public List<DocTransfer> getDocTransfer() {
            if (docTransfer == null) {
                docTransfer = new ArrayList<DocTransfer>();
            }
            return this.docTransfer;
        }

        /**
         * Gets the value of the note property.
         * 
         * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the note property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
	 *
         * <pre>
         *    getNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Note }
         * 
         * 
         */
        public List<Note> getNote() {
            if (note == null) {
                note = new ArrayList<Note>();
            }
            return this.note;
        }

        /**
         * Gets the value of the referred property.
         * 
         * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the referred property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
	 *
         * <pre>
         *    getReferred().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Referred }
         * 
         * 
         */
        public List<Referred> getReferred() {
            if (referred == null) {
                referred = new ArrayList<Referred>();
            }
            return this.referred;
        }

	public String getContents() {
	    return this.contents;
	}

	public void setContents(String contents) {
	    this.contents = contents;
	}

        /**
         * Gets the value of the addType property.
         * 
         */
	public FolderAddType getAddType() {
            return addType;
        }

        /**
         * Sets the value of the addType property.
         * 
         */
	public void setAddType(FolderAddType value) {
            this.addType = value;
        }

    }

}
