/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.07 at 04:32:17 PM MSD
//


package com.aplana.dmsi.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="street" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="house" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="building" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="flat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settlement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="district" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postbox" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nontypical" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "Address")
public class Address {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected String street;
    @XmlAttribute
    protected String house;
    @XmlAttribute
    protected String building;
    @XmlAttribute
    protected String flat;
    @XmlAttribute
    protected String settlement;
    @XmlAttribute
    protected String district;
    @XmlAttribute
    protected String region;
    @XmlAttribute
    protected String country;
    @XmlAttribute
    protected String postcode;
    @XmlAttribute
    protected String postbox;
    @XmlAttribute
    protected String nontypical;

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the street property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the house property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHouse() {
        return house;
    }

    /**
     * Sets the value of the house property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHouse(String value) {
        this.house = value;
    }

    /**
     * Gets the value of the building property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBuilding(String value) {
        this.building = value;
    }

    /**
     * Gets the value of the flat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFlat() {
        return flat;
    }

    /**
     * Sets the value of the flat property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFlat(String value) {
        this.flat = value;
    }

    /**
     * Gets the value of the settlement property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSettlement() {
        return settlement;
    }

    /**
     * Sets the value of the settlement property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSettlement(String value) {
        this.settlement = value;
    }

    /**
     * Gets the value of the district property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the region property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the post�ode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * Sets the value of the post�ode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPostcode(String value) {
        this.postcode = value;
    }

    /**
     * Gets the value of the postbox property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPostbox() {
        return postbox;
    }

    /**
     * Sets the value of the postbox property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPostbox(String value) {
        this.postbox = value;
    }

    /**
     * Gets the value of the nontypical property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNontypical() {
        return nontypical;
    }

    /**
     * Sets the value of the nontypical property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNontypical(String value) {
        this.nontypical = value;
    }

}
