/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.07 at 04:32:17 PM MSD
//

package com.aplana.dmsi.types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base=&quot;&lt;http://www.w3.org/2001/XMLSchema&gt;base64Binary&quot;&gt;
 *       &lt;attribute name=&quot;os&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;type&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;type_ver&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;char_set&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;description&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;transfertype&quot; use=&quot;required&quot; type=&quot;{}TransferEnumType&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "", propOrder = { "value" })
@XmlRootElement(name = "DocTransfer")
public class DocTransfer extends DMSIObject {

    protected byte[] value;
    protected String os = System.getProperty("os.name");
    protected String type = "";
    protected String typeVer;
    protected String charSet;
    protected String description = "";
    protected TransferEnumType transfertype = TransferEnumType.FILE;
    protected List<EDS> eds;
    protected String uid;
    protected String incomeDateAttributeName;
    protected Date incomeDate;
    protected String isPrimeAttributeName;
    protected String isPrime;
    protected IsPrimeEnumType isPrimeId;
    protected String nameAttributeName;
    protected String name;
    protected String authorAttributeName;
    protected PrivatePerson author;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is byte[]
     */
    @XmlSchemaType(name = "base64Binary")
    @XmlValue
    public byte[] getValue() {
	return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *                allowed object is byte[]
     */
    public void setValue(byte[] value) {
	this.value = value;
    }

    /**
     * Gets the value of the os property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute(required = true)
    public String getOs() {
	return os;
    }

    /**
     * Sets the value of the os property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setOs(String value) {
	this.os = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute(required = true)
    public String getType() {
	return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setType(String value) {
	this.type = value;
    }

    /**
     * Gets the value of the typeVer property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute(name = "type_ver")
    public String getTypeVer() {
	return typeVer;
    }

    /**
     * Sets the value of the typeVer property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setTypeVer(String value) {
	this.typeVer = value;
    }

    /**
     * Gets the value of the charSet property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute(name = "char_set")
    public String getCharSet() {
	return charSet;
    }

    /**
     * Sets the value of the charSet property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setCharSet(String value) {
	this.charSet = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute(required = true)
    public String getDescription() {
	return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
	this.description = value;
    }

    /**
     * Gets the value of the transfertype property.
     *
     */
    @XmlAttribute(required = true)
    public TransferEnumType getTransfertype() {
	return transfertype;
    }

    /**
     * Sets the value of the transfertype property.
     *
     */
    public void setTransfertype(TransferEnumType value) {
	this.transfertype = value;
    }

    @XmlTransient
    public List<EDS> getEds() {
	if (this.eds == null) {
	    this.eds = new ArrayList<EDS>();
	}
	return this.eds;
    }

    @XmlTransient
    public String getUid() {
	return this.uid;
}

    public void setUid(String uuid) {
	this.uid = uuid;
    }

    @XmlTransient
    public String getIncomeDateAttributeName() {
        return this.incomeDateAttributeName;
    }

    @XmlTransient
    public Date getIncomeDate() {
        return this.incomeDate;
    }

    @XmlTransient
    public String getIsPrimeAttributeName() {
        return this.isPrimeAttributeName;
    }

    @XmlTransient
    public String getIsPrime() {
        return this.isPrime;
    }

    @XmlTransient
    public IsPrimeEnumType getIsPrimeId() {
        return this.isPrimeId;
    }
    
    public void setIsPrimeId(IsPrimeEnumType isPrimeId) {
        this.isPrimeId = isPrimeId;
    }
 
    @XmlTransient
    public String getNameAttributeName() {
        return this.nameAttributeName;
    }

    @XmlTransient
    public String getName() {
        return this.name;
    }

    @XmlTransient
    public String getAuthorAttributeName() {
        return this.authorAttributeName;
    }

    @XmlTransient
    public PrivatePerson getAuthor() {
        return this.author;
    }


}
