/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.07 at 04:32:17 PM MSD
//

package com.aplana.dmsi.types;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.aplana.dmsi.types.adapters.DocTransferAdapter;
import com.aplana.dmsi.types.adapters.DocTypeAdapter;
import com.aplana.dmsi.types.common.DocType;

/**
 * <p>
 * Java class for DocumentType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name=&quot;DocumentType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}RegNumber&quot;/&gt;
 *         &lt;element ref=&quot;{}Confident&quot;/&gt;
 *         &lt;element ref=&quot;{}Referred&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}DocNumber&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}Addressee&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}DocTransfer&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}RegHistory&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}Author&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *         &lt;element ref=&quot;{}Validator&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}Writer&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;idnumber&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;type&quot; use=&quot;required&quot; type=&quot;{}DocumentEnumType&quot; /&gt;
 *       &lt;attribute name=&quot;kind&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;pages&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}unsignedLong&quot; /&gt;
 *       &lt;attribute name=&quot;title&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;annotation&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;collection&quot; type=&quot;{}CollectionEnumType&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "DocumentType", propOrder = { "regNumber", "confident",
        "referred", "docNumber", "addressee", "docTransfer", "regHistory",
        "author", "validator", "writer" })
public class DocumentType extends DMSIObject {

    protected RegNumber regNumber = new RegNumber();
    protected Confident confident = new Confident();
    protected List<Referred> referred;
    protected List<DocNumber> docNumber;
    protected List<Addressee> addressee;
    protected List<DocTransfer> docTransfer;
    protected List<RegHistory> regHistory;
    protected List<Author> author;
    protected List<Validator> validator;
    protected Writer writer;
    protected String idnumber = "";
    protected byte type;
    protected DocType kind;
    protected BigInteger pages;
    protected String title;
    protected String annotation;
    protected CollectionEnumType collection;
    protected String tasksDescription;
    protected String uid;
    protected TaskListType taskList;
    protected List<Rubric> rubric;


    /**
     * Gets the value of the regNumber property.
     *
     * @return possible object is {@link RegNumber }
     *
     */
    @XmlElement(name = "RegNumber", required = true)
    public RegNumber getRegNumber() {
        return regNumber;
    }

    /**
     * Sets the value of the regNumber property.
     *
     * @param value
     *                allowed object is {@link RegNumber }
     *
     */
    public void setRegNumber(RegNumber value) {
        this.regNumber = value;
    }

    /**
     * Gets the value of the confident property.
     *
     * @return possible object is {@link Confident }
     *
     */
    @XmlElement(name = "Confident", required = true)
    public Confident getConfident() {
        return confident;
    }

    /**
     * Sets the value of the confident property.
     *
     * @param value
     *                allowed object is {@link Confident }
     *
     */
    public void setConfident(Confident value) {
        this.confident = value;
    }

    /**
     * Gets the value of the referred property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the referred property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getReferred().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Referred }
     *
     *
     */
    @XmlElement(name = "Referred")
    public List<Referred> getReferred() {
        if (referred == null) {
            referred = new ArrayList<Referred>();
        }
        return this.referred;
    }

    /**
     * Gets the value of the docNumber property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the docNumber property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDocNumber().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocNumber }
     *
     *
     */
    @XmlElement(name = "DocNumber")
    public List<DocNumber> getDocNumber() {
        if (docNumber == null) {
            docNumber = new ArrayList<DocNumber>();
        }
        return this.docNumber;
    }

    /**
     * Gets the value of the addressee property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the addressee property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getAddressee().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Addressee }
     *
     *
     */
    @XmlElement(name = "Addressee")
    public List<Addressee> getAddressee() {
        if (addressee == null) {
            addressee = new ArrayList<Addressee>();
        }
        return this.addressee;
    }

    /**
     * Gets the value of the docTransfer property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the docTransfer property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDocTransfer().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocTransfer }
     *
     *
     */
    @XmlElement(name = "DocTransfer")
    @XmlJavaTypeAdapter(DocTransferAdapter.class)
    public List<DocTransfer> getDocTransfer() {
        if (docTransfer == null) {
            docTransfer = new ArrayList<DocTransfer>();
        }
        return this.docTransfer;
    }

    /**
     * Gets the value of the regHistory property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the regHistory property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getRegHistory().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegHistory }
     *
     *
     */
    @XmlElement(name = "RegHistory")
    public List<RegHistory> getRegHistory() {
        if (regHistory == null) {
            regHistory = new ArrayList<RegHistory>();
        }
        return this.regHistory;
    }

    /**
     * Gets the value of the author property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the author property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getAuthor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Author }
     *
     *
     */
    @XmlElement(name = "Author", required = true)
    public List<Author> getAuthor() {
        if (author == null) {
            author = new ArrayList<Author>();
        }
        return this.author;
    }

    /**
     * Gets the value of the validator property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the validator property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getValidator().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Validator }
     *
     *
     */
    @XmlElement(name = "Validator")
    public List<Validator> getValidator() {
        if (validator == null) {
            validator = new ArrayList<Validator>();
        }
        return this.validator;
    }

    /**
     * Gets the value of the writer property.
     *
     * @return possible object is {@link Writer }
     *
     */
    @XmlElement(name = "Writer")
    public Writer getWriter() {
        return writer;
    }

    /**
     * Sets the value of the writer property.
     *
     * @param value
     *                allowed object is {@link Writer }
     *
     */
    public void setWriter(Writer value) {
        this.writer = value;
    }

    /**
     * Gets the value of the idnumber property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute(required = true)
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * Sets the value of the idnumber property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setIdnumber(String value) {
        this.idnumber = value;
    }

    /**
     * Gets the value of the type property.
     *
     */
    @XmlAttribute(required = true)
    public byte getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     */
    public void setType(byte value) {
        this.type = value;
    }

    /**
     * Gets the value of the kind property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute
    @XmlJavaTypeAdapter(DocTypeAdapter.class)
    public DocType getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setKind(DocType value) {
        this.kind = value;
    }

    /**
     * Gets the value of the pages property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    @XmlAttribute
    @XmlSchemaType(name = "unsignedLong")
    public BigInteger getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     *
     * @param value
     *                allowed object is {@link BigInteger }
     *
     */
    public void setPages(BigInteger value) {
        this.pages = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the annotation property.
     *
     * @return possible object is {@link String }
     *
     */
    @XmlAttribute
    public String getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setAnnotation(String value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the collection property.
     *
     * @return possible object is {@link Byte }
     *
     */
    @XmlAttribute
    public CollectionEnumType getCollection() {
        return collection;
    }

    /**
     * Sets the value of the collection property.
     *
     * @param value
     *                allowed object is {@link Byte }
     *
     */
    public void setCollection(CollectionEnumType value) {
        this.collection = value;
    }

    @XmlTransient
    public String getTasksDescription() {
        return this.tasksDescription;
    }

    public void setTasksDescription(String tasksDescription) {
        this.tasksDescription = tasksDescription;
    }

    @XmlTransient
    public String getUid() {
	return this.uid;
    }

    public void setUid(String uuid) {
	this.uid = uuid;
    }

    @XmlTransient
    public List<Rubric> getRubric() {
        if (this.rubric == null) {
            this.rubric = new ArrayList<Rubric>();
        }
        return this.rubric;
    }

    @XmlTransient
    public TaskListType getTaskList() {
        return this.taskList;
    }

    public void setTaskList(TaskListType taskList) {
        this.taskList = taskList;
    }

}
