/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.07 at 04:32:17 PM MSD
//

package com.aplana.dmsi.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.aplana.dmsi.types.adapters.DepartmentAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base=&quot;&lt;http://www.w3.org/2001/XMLSchema&gt;string&quot;&gt;
 *       &lt;attribute name=&quot;department&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;post&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;separator&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "value" })
@XmlRootElement(name = "Official")
public class Official extends DMSIObject {

    @XmlValue
    protected String value;
    @XmlAttribute
    @XmlJavaTypeAdapter(DepartmentAdapter.class)
    protected Department department;
    @XmlAttribute
    protected String post;
    @XmlAttribute
    protected String separator;

    public Official() {
    }

    public Official(Official another) {
	setValue(another.getValue());
	setDepartment(another.getDepartment());
	setPost(another.getPost());
	setSeparator(another.getSeparator());
	setId(another.getId());
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValue() {
	return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setValue(String value) {
	this.value = value;
    }

    /**
     * Gets the value of the department property.
     *
     * @return possible object is {@link String }
     *
     */
    public Department getDepartment() {
	return department;
    }

    /**
     * Sets the value of the department property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setDepartment(Department value) {
	this.department = value;
    }

    /**
     * Gets the value of the post property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPost() {
	return post;
    }

    /**
     * Sets the value of the post property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setPost(String value) {
	this.post = value;
    }

    /**
     * Gets the value of the separator property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSeparator() {
	return separator;
    }

    /**
     * Sets the value of the separator property.
     *
     * @param value
     *                allowed object is {@link String }
     *
     */
    public void setSeparator(String value) {
	this.separator = value;
    }

}
