/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.07 at 04:32:17 PM MSD
//

package com.aplana.dmsi.types;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}Address&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}Econtact&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{}OfficialPerson&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;organization_string&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;fullname&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;shortname&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;ownership&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;ogrn&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}unsignedLong&quot; /&gt;
 *       &lt;attribute name=&quot;inn&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}unsignedLong&quot; /&gt;
 *       &lt;attribute name=&quot;kpp&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}unsignedLong&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "", propOrder = { "address", "econtact", "officialPerson" })
@XmlRootElement(name = "Organization")
public class Organization extends DMSIObject {

    private OrganizationOnly organization = new OrganizationOnly();
    protected List<OfficialPerson> officialPerson;

    public Organization() {
    }

    @XmlTransient
    @Override
    public String getId() {
    	String selfId = super.getId();
    	return selfId == null || "".equals(selfId) ? organization.getId() : selfId;
    }

    public Organization(OrganizationOnly organization) {
	this.organization = organization;
    }

    protected OrganizationOnly getOrganization() {
	return this.organization;
    }

    @XmlElement(name = "Address")
    public Address getAddress() {
	return organization.getAddress();
    }

    public void setAddress(Address value) {
	organization.setAddress(value);
    }

    @XmlElement(name = "Econtact")
    public List<Econtact> getEcontact() {
	return organization.getEcontact();
    }

    @XmlElement(name = "OfficialPerson")
    public List<OfficialPerson> getOfficialPerson() {
	if (officialPerson == null) {
	    officialPerson = new ArrayList<OfficialPerson>();
	}
	return this.officialPerson;
    }

    @XmlAttribute(name = "organization_string", required = true)
    public String getOrganizationString() {
	return organization.getOrganizationString();
    }

    public void setOrganizationString(String value) {
	organization.setOrganizationString(value);
    }

    @XmlAttribute(name = "fullname")
    public String getFullname() {
	return organization.getFullname();
    }

    public void setFullname(String value) {
	organization.setFullname(value);
    }

    @XmlAttribute(name = "shortname")
    public String getShortname() {
	return organization.getShortname();
    }

    public void setShortname(String value) {
	organization.setShortname(value);
    }

    @XmlAttribute(name = "ownership")
    public String getOwnership() {
	return organization.getOwnership();
    }

    public void setOwnership(String value) {
	organization.setOwnership(value);
    }

    @XmlAttribute
    @XmlSchemaType(name = "unsignedLong")
    public BigInteger getOgrn() {
	return organization.getOgrn();
    }

    public void setOgrn(BigInteger value) {
	organization.setOgrn(value);
    }

    @XmlAttribute
    @XmlSchemaType(name = "unsignedLong")
    public BigInteger getInn() {
	return organization.getInn();
    }

    public void setInn(BigInteger value) {
	organization.setInn(value);
    }

    @XmlAttribute
    @XmlSchemaType(name = "unsignedLong")
    public BigInteger getKpp() {
	return organization.getKpp();
    }

    public void setKpp(BigInteger value) {
	organization.setKpp(value);
    }

    @XmlTransient
    public String getOrganizationid() {
	return organization.getOrganizationid();
    }

    public void setOrganizationid(String organizationid) {
	organization.setOrganizationid(organizationid);
    }

    public OrganizationOnly getSourcedOrganization() {
    	return this.organization;
    }
}
