/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package com.aplana.ws.soz.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.aplana.ws.soz.model.attachement.PutDMSMessageRequest;
import com.aplana.ws.soz.model.attachement.PutDMSMessageResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DMSExchangePortType", targetNamespace = "urn://x-artefacts-it-ru/dob/poltava/dmsx/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.aplana.ws.soz.model.communication.ObjectFactory.class,
    com.aplana.ws.soz.model.attachement.ObjectFactory.class
})
public interface DMSExchangePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.aplana.ws.soz.model.attachement.PutDMSMessageResponse
     */
    @WebMethod(action = "urn:putDMSMessage")
    @WebResult(name = "putDMSMessageResponse", targetNamespace = "urn://x-artefacts-it-ru/dob/poltava/dmsx/1.0", partName = "parameters")
    public PutDMSMessageResponse putDMSMessage(
        @WebParam(name = "putDMSMessageRequest", targetNamespace = "urn://x-artefacts-it-ru/dob/poltava/dmsx/1.0", partName = "parameters")
        PutDMSMessageRequest parameters);

}
