/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package com.aplana.dbmi.ws.zdproblemsserviceproxy;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ZoneDowProblemsService", targetNamespace = "http://aplana.com/dbmi/ws/ZoneDowProblemsService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZoneDowProblemsService {


    /**
     * 
     * @return
     *     returns com.aplana.dbmi.ws.zdproblemsserviceproxy.ZoneDowProblemsResponse
     */
    @WebMethod
    @WebResult(name = "zoneDowProblemsServiceResponse", targetNamespace = "")
    @RequestWrapper(localName = "getZDProblemOrgsStat", targetNamespace = "http://aplana.com/dbmi/ws/ZoneDowProblemsService", className = "com.aplana.dbmi.ws.zdproblemsserviceproxy.GetZDProblemOrgsStat")
    @ResponseWrapper(localName = "getZDProblemOrgsStatResponse", targetNamespace = "http://aplana.com/dbmi/ws/ZoneDowProblemsService", className = "com.aplana.dbmi.ws.zdproblemsserviceproxy.GetZDProblemOrgsStatResponse")
    public ZoneDowProblemsResponse getZDProblemOrgsStat();

}
