/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package ru.it.fsfr.services.dbmi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "DBMIStartReglamentService", targetNamespace = "http://services.fsfr.it.ru/DBMI", wsdlLocation = "http://kgerman-note:8088/interoperability.DBMIStartReglamentService-1.0/DBMIStartReglamentService?wsdl")
public class DBMIStartReglamentService
    extends Service
{

    private final static URL DBMISTARTREGLAMENTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://kgerman-note:8088/interoperability.DBMIStartReglamentService-1.0/DBMIStartReglamentService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        DBMISTARTREGLAMENTSERVICE_WSDL_LOCATION = url;
    }

    public DBMIStartReglamentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DBMIStartReglamentService() {
        super(DBMISTARTREGLAMENTSERVICE_WSDL_LOCATION, new QName("http://services.fsfr.it.ru/DBMI", "DBMIStartReglamentService"));
    }

    /**
     * 
     * @return
     *     returns IDBMIStartReglamentService
     */
    @WebEndpoint(name = "DBMIStartReglamentServicePort")
    public IDBMIStartReglamentService getDBMIStartReglamentServicePort() {
        return (IDBMIStartReglamentService)super.getPort(new QName("http://services.fsfr.it.ru/DBMI", "DBMIStartReglamentServicePort"), IDBMIStartReglamentService.class);
    }

}
