/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package ru.it.fsfr.services.dbmi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IDBMIStartReglamentService", targetNamespace = "http://services.fsfr.it.ru/DBMI")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IDBMIStartReglamentService {


    /**
     * 
     * @param card
     * @param file
     */
    @WebMethod
    public void startReglamentByCard(
        @WebParam(name = "card", partName = "card")
        String card,
        @WebParam(name = "file", partName = "file")
        File file);

}
