/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package com.aplana.ireferent.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.aplana.ireferent.types.WSOCollection;
import com.aplana.ireferent.types.WSOContext;
import com.aplana.ireferent.types.WSOGroup;
import com.aplana.ireferent.types.WSOPerson;
import com.aplana.ireferent.types.WSObject;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 *
 */
@WebService(name = "WS_StaffManager", targetNamespace = "urn:DefaultNamespace")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSStaffManager {

    @WebMethod(operationName = "GETGROUP")
    @WebResult(name = "GETGROUPReturn", partName = "GETGROUPReturn")
    public WSOGroup getGroup(
        @WebParam(name = "ID", partName = "ID")
        String groupId,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeAttachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOContext context);

    @WebMethod(operationName = "GETPERSON")
    @WebResult(name = "GETPERSONReturn", partName = "GETPERSONReturn")
    public WSOPerson getPerson(
        @WebParam(name = "ID", partName = "ID")
        String personId,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeAttachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOContext context);
    
    @WebMethod(operationName = "GETPERSONID")
    @WebResult(name = "GETPERSONIDReturn", partName = "GETPERSONIDReturn")
    public WSObject getPersonId(
        @WebParam(name = "PERSONLOGIN", partName = "PERSONLOGIN")
        String personLogin);

    @WebMethod(operationName = "GETORGANIZATIONS")
    @WebResult(name = "GETORGANIZATIONSReturn", partName = "GETORGANIZATIONSReturn")
    public WSOCollection getOrganizations(
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean isMObject,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeAttachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOContext context);

    @WebMethod(operationName = "GETPERSONS")
    @WebResult(name = "GETPERSONSReturn", partName = "GETPERSONSReturn")
    public WSOCollection getPersons(
        @WebParam(name = "GROUPID", partName = "GROUPID")
        String groupId,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean isMObject,
        @WebParam(name = "CHILDSLEVEL", partName = "CHILDSLEVEL")
        Integer childsLevel,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeAttachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOContext context);

    @WebMethod(operationName = "GETSTRUCTURE")
    @WebResult(name = "GETSTRUCTUREReturn", partName = "GETSTRUCTUREReturn")
    public WSOGroup getStructure(
        @WebParam(name = "GROUPID", partName = "GROUPID")
        String groupId,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean isMObject,
        @WebParam(name = "CHILDSLEVEL", partName = "CHILDSLEVEL")
        Integer childsLevel,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeAttachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOContext context);
}
