/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package com.aplana.dbmi.ws.docstatisticserviceproxy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocsStatisticServiceImplService", targetNamespace = "http://impl.ws.dbmi.aplana.com/", wsdlLocation = "file:/D:/jbossportal/server/default/tmp/jbossws/DocsStatisticServiceImplService2300123886885483662.wsdl")
public class DocsStatisticServiceImplService
    extends Service
{

    private final static URL DOCSSTATISTICSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.aplana.dbmi.ws.docstatisticserviceproxy.DocsStatisticServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.aplana.dbmi.ws.docstatisticserviceproxy.DocsStatisticServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/jbossportal/server/default/tmp/jbossws/DocsStatisticServiceImplService2300123886885483662.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/jbossportal/server/default/tmp/jbossws/DocsStatisticServiceImplService2300123886885483662.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCSSTATISTICSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DocsStatisticServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocsStatisticServiceImplService() {
        super(DOCSSTATISTICSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.ws.dbmi.aplana.com/", "DocsStatisticServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns DocsStatisticService
     */
    @WebEndpoint(name = "DocsStatisticServiceImplPort")
    public DocsStatisticService getDocsStatisticServiceImplPort() {
        return super.getPort(new QName("http://impl.ws.dbmi.aplana.com/", "DocsStatisticServiceImplPort"), DocsStatisticService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocsStatisticService
     */
    @WebEndpoint(name = "DocsStatisticServiceImplPort")
    public DocsStatisticService getDocsStatisticServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.dbmi.aplana.com/", "DocsStatisticServiceImplPort"), DocsStatisticService.class, features);
    }

}
