/**
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements.  See the NOTICE file distributed with
 *   this work for additional information regarding copyright ownership.
 *   The ASF licenses this file to you under the Apache License, Version 2.0
 *   (the "License"); you may not use this file except in compliance with
 *   the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package com.aplana.dbmi.ws.docstatisticserviceproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocsStatisticService", targetNamespace = "http://aplana.com/dbmi/ws/DocsStatisticService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocsStatisticService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.aplana.dbmi.ws.docstatisticserviceproxy.DocsStatisticResponse
     */
    @WebMethod
    @WebResult(name = "docsStatisticResponse", targetNamespace = "")
    @RequestWrapper(localName = "getDocumentsStatistic", targetNamespace = "http://aplana.com/dbmi/ws/DocsStatisticService", className = "com.aplana.dbmi.ws.docstatisticserviceproxy.GetDocumentsStatistic")
    @ResponseWrapper(localName = "getDocumentsStatisticResponse", targetNamespace = "http://aplana.com/dbmi/ws/DocsStatisticService", className = "com.aplana.dbmi.ws.docstatisticserviceproxy.GetDocumentsStatisticResponse")
    public DocsStatisticResponse getDocumentsStatistic(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2);

}
